version: "3"

services:
  backend:
    build: ./backend
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./backend/:/app/backend 
    ports: 
      - "80:8000"
  frontend:
    build: ./frontend/
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "30:3000"

volumes:
  node-modules: