version: "3"

services:
  backend:
    platform: linux/amd64
    build: ./backend
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - backend-volume:/app/backend 
      - frontend-volume:/app/frontend
    ports: 
      - "8000:8000"
  frontend:
    platform: linux/amd64
    build: ./frontend/
    command: ["npm", "start"]
    volumes:
      - frontend-volume:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"

volumes:
  node-modules:
  frontend-volume:
  backend-volume: